name              "warehouse"
maintainer        "Donald Stufft"
maintainer_email  "donald@stufft.io"
license           "Apache 2.0"
description       "Install and configure Warehouse"
version           "0.0.12"

depends "apt"
depends "python"
depends "git"
depends "postgresql"
depends "gunicorn"
depends "supervisor"
depends "nginx"
depends "nodejs"
