site :opscode

cookbook "apt"
cookbook "chef-client"
cookbook "sudo"
cookbook "jn_sysctl"
cookbook "heartbeat", :git => "https://github.com/coderanger/heartbeat.git"
cookbook "ntp"
cookbook "motd-tail"
cookbook "build-essential"
cookbook "zsh"
cookbook "application"
cookbook "application_python", :git => "https://github.com/coderanger/application_python-1.git", :ref => "patch-1"
cookbook "application_nginx"
cookbook "apache2"
cookbook "postfix"
cookbook "mercurial", :git => "https://github.com/coderanger/mercurial.git", :ref => "lwrp-updates"
cookbook "openssh"
cookbook "java"
cookbook "runit"
cookbook "riemann", :git => "https://github.com/benjaminws/riemann-chef.git", :ref => "a6882ef7bad0d842f42f2fa97acbefd7d0d29c38"
cookbook "memcached"
cookbook "graphite", :git => "git://github.com/hw-cookbooks/graphite.git", :ref => "39b0e35d437a7a8d4a8ce09e2617fdda4c917801"
cookbook "collectd", :git => "https://github.com/miah/chef-collectd.git", :ref => "tags/1.0.8"
cookbook "firewall"
