name              "psf-debbuild"
maintainer        "Donald Stufft"
maintainer_email  "donald@stufft.io"
license           "Apache 2.0"
description       "Installs and configures builders"
version           "0.0.19"

depends           "reprepro"
depends           "poise"
depends           "jenkins"
depends           "postgresql"
