name              "rsnapshot"
maintainer        "Noah Kantrowitz"
maintainer_email  "noah@coderanger.net"
license           "Apache 2.0"
description       "Install and configure rsnapshot server and clients"
version           "0.0.2"
