name              "psf-monitoring"
maintainer        "Benjamin W. Smith"
maintainer_email  "benjaminwarfield@just-another.net"
license           "Apache 2.0"
description       "Install and configure Monitoring Tools"
version           "0.0.3"

depends "riemann"
depends "runit"
depends "graphite"
depends "apt"
depends "collectd"
depends "firewall"
