name              "stud"
maintainer        "Benjamin W. Smith"
maintainer_email  "benjaminwarfield@just-another.net"
license           "Apache 2.0"
description       "Install and configure stud"
version           "0.0.2"
