#!/bin/bash

IP_ADDR="$1"

if [[ ${IP_ADDR} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
  echo "Cleaning up denyhosts for ${IP_ADDR}"
else
  echo "Sorry, you did not provide an actual ip address"
  exit 1
fi

service denyhosts stop

for file in /var/lib/denyhosts/*; do
  sed -i "/${IP_ADDR}/d" "$file"
done

sed -i "/${IP_ADDR}/d" /etc/hosts.deny

service denyhosts start
