name              "pgbouncer"
maintainer        "Noah Kantrowitz"
maintainer_email  "noah@coderanger.net"
license           "Apache 2.0"
description       "Install and configure pgbouncer"
version           "0.0.1"
