name              "psf-pypi"
maintainer        "Noah Kantrowitz"
maintainer_email  "noah@coderanger.net"
license           "Apache 2.0"
description       "Installs and configures PyPI"
version           "0.0.21"

depends           "pgbouncer"
depends           "rsyslog"
depends           "postgresql"
depends           "mercurial"
depends           "python"
depends           "nginx"
depends           "supervisor"
depends           "gunicorn"
depends           "sysctl"
